[project]
name = "league-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=1.8.3",
    "kagglehub>=0.4.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "tensorflow>=2.20.0",
]
